//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineTrip {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Private : global::System.Configuration.ApplicationSettingsBase {
        
        private static Private defaultInstance = ((Private)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Private())));
        
        public static Private Default {
            get {
                return defaultInstance;
            }
        }
    }
}
